/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScholarshipRouteImport } from './routes/scholarship'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesVirtualAssistantProgrammeRouteImport } from './routes/courses.virtual-assistant-programme'
import { Route as CoursesScrumMasterRouteImport } from './routes/courses.scrum-master'
import { Route as CoursesProjectManagementBusinessAnalysisRouteImport } from './routes/courses.project-management-business-analysis'
import { Route as CoursesProductManagementRouteImport } from './routes/courses.product-management'
import { Route as CoursesDigitalMarketingRouteImport } from './routes/courses.digital-marketing'
import { Route as CoursesDataAnalysisRouteImport } from './routes/courses.data-analysis'
import { Route as CoursesCybersecurityRouteImport } from './routes/courses.cybersecurity'
import { Route as CoursesAiForProfessionalsRouteImport } from './routes/courses.ai-for-professionals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInstructorIndexRouteImport } from './routes/_authenticated/instructor.index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedInstructorUploadRouteImport } from './routes/_authenticated/instructor.upload'
import { Route as AuthenticatedInstructorStudentsRouteImport } from './routes/_authenticated/instructor.students'
import { Route as AuthenticatedInstructorCoursesRouteImport } from './routes/_authenticated/instructor.courses'
import { Route as AuthenticatedInstructorCapstonesRouteImport } from './routes/_authenticated/instructor.capstones'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardCoursesRouteImport } from './routes/_authenticated/dashboard.courses'
import { Route as AuthenticatedDashboardCertificatesRouteImport } from './routes/_authenticated/dashboard.certificates'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin.students'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminLessonsRouteImport } from './routes/_authenticated/admin.lessons'
import { Route as AuthenticatedAdminInquiriesRouteImport } from './routes/_authenticated/admin.inquiries'
import { Route as AuthenticatedAdminEnrollmentsRouteImport } from './routes/_authenticated/admin.enrollments'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin.courses'
import { Route as AuthenticatedAdminCohortsRouteImport } from './routes/_authenticated/admin.cohorts'
import { Route as AuthenticatedAdminCertificatesRouteImport } from './routes/_authenticated/admin.certificates'
import { Route as AuthenticatedAdminCapstonesRouteImport } from './routes/_authenticated/admin.capstones'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin.announcements'
import { Route as AuthenticatedDashboardCoursesSlugRouteImport } from './routes/_authenticated/dashboard.courses.$slug'

const ScholarshipRoute = ScholarshipRouteImport.update({
  id: '/scholarship',
  path: '/scholarship',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesVirtualAssistantProgrammeRoute =
  CoursesVirtualAssistantProgrammeRouteImport.update({
    id: '/virtual-assistant-programme',
    path: '/virtual-assistant-programme',
    getParentRoute: () => CoursesRoute,
  } as any)
const CoursesScrumMasterRoute = CoursesScrumMasterRouteImport.update({
  id: '/scrum-master',
  path: '/scrum-master',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesProjectManagementBusinessAnalysisRoute =
  CoursesProjectManagementBusinessAnalysisRouteImport.update({
    id: '/project-management-business-analysis',
    path: '/project-management-business-analysis',
    getParentRoute: () => CoursesRoute,
  } as any)
const CoursesProductManagementRoute =
  CoursesProductManagementRouteImport.update({
    id: '/product-management',
    path: '/product-management',
    getParentRoute: () => CoursesRoute,
  } as any)
const CoursesDigitalMarketingRoute = CoursesDigitalMarketingRouteImport.update({
  id: '/digital-marketing',
  path: '/digital-marketing',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesDataAnalysisRoute = CoursesDataAnalysisRouteImport.update({
  id: '/data-analysis',
  path: '/data-analysis',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesCybersecurityRoute = CoursesCybersecurityRouteImport.update({
  id: '/cybersecurity',
  path: '/cybersecurity',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesAiForProfessionalsRoute =
  CoursesAiForProfessionalsRouteImport.update({
    id: '/ai-for-professionals',
    path: '/ai-for-professionals',
    getParentRoute: () => CoursesRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInstructorIndexRoute =
  AuthenticatedInstructorIndexRouteImport.update({
    id: '/instructor/',
    path: '/instructor/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInstructorUploadRoute =
  AuthenticatedInstructorUploadRouteImport.update({
    id: '/instructor/upload',
    path: '/instructor/upload',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstructorStudentsRoute =
  AuthenticatedInstructorStudentsRouteImport.update({
    id: '/instructor/students',
    path: '/instructor/students',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstructorCoursesRoute =
  AuthenticatedInstructorCoursesRouteImport.update({
    id: '/instructor/courses',
    path: '/instructor/courses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstructorCapstonesRoute =
  AuthenticatedInstructorCapstonesRouteImport.update({
    id: '/instructor/capstones',
    path: '/instructor/capstones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCoursesRoute =
  AuthenticatedDashboardCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCertificatesRoute =
  AuthenticatedDashboardCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/admin/students',
    path: '/admin/students',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLessonsRoute =
  AuthenticatedAdminLessonsRouteImport.update({
    id: '/admin/lessons',
    path: '/admin/lessons',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminInquiriesRoute =
  AuthenticatedAdminInquiriesRouteImport.update({
    id: '/admin/inquiries',
    path: '/admin/inquiries',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminEnrollmentsRoute =
  AuthenticatedAdminEnrollmentsRouteImport.update({
    id: '/admin/enrollments',
    path: '/admin/enrollments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/admin/courses',
    path: '/admin/courses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCohortsRoute =
  AuthenticatedAdminCohortsRouteImport.update({
    id: '/admin/cohorts',
    path: '/admin/cohorts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCertificatesRoute =
  AuthenticatedAdminCertificatesRouteImport.update({
    id: '/admin/certificates',
    path: '/admin/certificates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCapstonesRoute =
  AuthenticatedAdminCapstonesRouteImport.update({
    id: '/admin/capstones',
    path: '/admin/capstones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/admin/announcements',
    path: '/admin/announcements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardCoursesSlugRoute =
  AuthenticatedDashboardCoursesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedDashboardCoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scholarship': typeof ScholarshipRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/courses/ai-for-professionals': typeof CoursesAiForProfessionalsRoute
  '/courses/cybersecurity': typeof CoursesCybersecurityRoute
  '/courses/data-analysis': typeof CoursesDataAnalysisRoute
  '/courses/digital-marketing': typeof CoursesDigitalMarketingRoute
  '/courses/product-management': typeof CoursesProductManagementRoute
  '/courses/project-management-business-analysis': typeof CoursesProjectManagementBusinessAnalysisRoute
  '/courses/scrum-master': typeof CoursesScrumMasterRoute
  '/courses/virtual-assistant-programme': typeof CoursesVirtualAssistantProgrammeRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/capstones': typeof AuthenticatedAdminCapstonesRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/cohorts': typeof AuthenticatedAdminCohortsRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/enrollments': typeof AuthenticatedAdminEnrollmentsRoute
  '/admin/inquiries': typeof AuthenticatedAdminInquiriesRoute
  '/admin/lessons': typeof AuthenticatedAdminLessonsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/dashboard/certificates': typeof AuthenticatedDashboardCertificatesRoute
  '/dashboard/courses': typeof AuthenticatedDashboardCoursesRouteWithChildren
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/instructor/capstones': typeof AuthenticatedInstructorCapstonesRoute
  '/instructor/courses': typeof AuthenticatedInstructorCoursesRoute
  '/instructor/students': typeof AuthenticatedInstructorStudentsRoute
  '/instructor/upload': typeof AuthenticatedInstructorUploadRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/instructor/': typeof AuthenticatedInstructorIndexRoute
  '/dashboard/courses/$slug': typeof AuthenticatedDashboardCoursesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scholarship': typeof ScholarshipRoute
  '/courses/ai-for-professionals': typeof CoursesAiForProfessionalsRoute
  '/courses/cybersecurity': typeof CoursesCybersecurityRoute
  '/courses/data-analysis': typeof CoursesDataAnalysisRoute
  '/courses/digital-marketing': typeof CoursesDigitalMarketingRoute
  '/courses/product-management': typeof CoursesProductManagementRoute
  '/courses/project-management-business-analysis': typeof CoursesProjectManagementBusinessAnalysisRoute
  '/courses/scrum-master': typeof CoursesScrumMasterRoute
  '/courses/virtual-assistant-programme': typeof CoursesVirtualAssistantProgrammeRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/capstones': typeof AuthenticatedAdminCapstonesRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/cohorts': typeof AuthenticatedAdminCohortsRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/enrollments': typeof AuthenticatedAdminEnrollmentsRoute
  '/admin/inquiries': typeof AuthenticatedAdminInquiriesRoute
  '/admin/lessons': typeof AuthenticatedAdminLessonsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/dashboard/certificates': typeof AuthenticatedDashboardCertificatesRoute
  '/dashboard/courses': typeof AuthenticatedDashboardCoursesRouteWithChildren
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/instructor/capstones': typeof AuthenticatedInstructorCapstonesRoute
  '/instructor/courses': typeof AuthenticatedInstructorCoursesRoute
  '/instructor/students': typeof AuthenticatedInstructorStudentsRoute
  '/instructor/upload': typeof AuthenticatedInstructorUploadRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/instructor': typeof AuthenticatedInstructorIndexRoute
  '/dashboard/courses/$slug': typeof AuthenticatedDashboardCoursesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scholarship': typeof ScholarshipRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/courses/ai-for-professionals': typeof CoursesAiForProfessionalsRoute
  '/courses/cybersecurity': typeof CoursesCybersecurityRoute
  '/courses/data-analysis': typeof CoursesDataAnalysisRoute
  '/courses/digital-marketing': typeof CoursesDigitalMarketingRoute
  '/courses/product-management': typeof CoursesProductManagementRoute
  '/courses/project-management-business-analysis': typeof CoursesProjectManagementBusinessAnalysisRoute
  '/courses/scrum-master': typeof CoursesScrumMasterRoute
  '/courses/virtual-assistant-programme': typeof CoursesVirtualAssistantProgrammeRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/capstones': typeof AuthenticatedAdminCapstonesRoute
  '/_authenticated/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/_authenticated/admin/cohorts': typeof AuthenticatedAdminCohortsRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/enrollments': typeof AuthenticatedAdminEnrollmentsRoute
  '/_authenticated/admin/inquiries': typeof AuthenticatedAdminInquiriesRoute
  '/_authenticated/admin/lessons': typeof AuthenticatedAdminLessonsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/dashboard/certificates': typeof AuthenticatedDashboardCertificatesRoute
  '/_authenticated/dashboard/courses': typeof AuthenticatedDashboardCoursesRouteWithChildren
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/instructor/capstones': typeof AuthenticatedInstructorCapstonesRoute
  '/_authenticated/instructor/courses': typeof AuthenticatedInstructorCoursesRoute
  '/_authenticated/instructor/students': typeof AuthenticatedInstructorStudentsRoute
  '/_authenticated/instructor/upload': typeof AuthenticatedInstructorUploadRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/instructor/': typeof AuthenticatedInstructorIndexRoute
  '/_authenticated/dashboard/courses/$slug': typeof AuthenticatedDashboardCoursesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/scholarship'
    | '/dashboard'
    | '/courses/ai-for-professionals'
    | '/courses/cybersecurity'
    | '/courses/data-analysis'
    | '/courses/digital-marketing'
    | '/courses/product-management'
    | '/courses/project-management-business-analysis'
    | '/courses/scrum-master'
    | '/courses/virtual-assistant-programme'
    | '/admin/announcements'
    | '/admin/capstones'
    | '/admin/certificates'
    | '/admin/cohorts'
    | '/admin/courses'
    | '/admin/enrollments'
    | '/admin/inquiries'
    | '/admin/lessons'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/students'
    | '/dashboard/certificates'
    | '/dashboard/courses'
    | '/dashboard/profile'
    | '/instructor/capstones'
    | '/instructor/courses'
    | '/instructor/students'
    | '/instructor/upload'
    | '/admin/'
    | '/dashboard/'
    | '/instructor/'
    | '/dashboard/courses/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/scholarship'
    | '/courses/ai-for-professionals'
    | '/courses/cybersecurity'
    | '/courses/data-analysis'
    | '/courses/digital-marketing'
    | '/courses/product-management'
    | '/courses/project-management-business-analysis'
    | '/courses/scrum-master'
    | '/courses/virtual-assistant-programme'
    | '/admin/announcements'
    | '/admin/capstones'
    | '/admin/certificates'
    | '/admin/cohorts'
    | '/admin/courses'
    | '/admin/enrollments'
    | '/admin/inquiries'
    | '/admin/lessons'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/students'
    | '/dashboard/certificates'
    | '/dashboard/courses'
    | '/dashboard/profile'
    | '/instructor/capstones'
    | '/instructor/courses'
    | '/instructor/students'
    | '/instructor/upload'
    | '/admin'
    | '/dashboard'
    | '/instructor'
    | '/dashboard/courses/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/scholarship'
    | '/_authenticated/dashboard'
    | '/courses/ai-for-professionals'
    | '/courses/cybersecurity'
    | '/courses/data-analysis'
    | '/courses/digital-marketing'
    | '/courses/product-management'
    | '/courses/project-management-business-analysis'
    | '/courses/scrum-master'
    | '/courses/virtual-assistant-programme'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/capstones'
    | '/_authenticated/admin/certificates'
    | '/_authenticated/admin/cohorts'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/enrollments'
    | '/_authenticated/admin/inquiries'
    | '/_authenticated/admin/lessons'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/students'
    | '/_authenticated/dashboard/certificates'
    | '/_authenticated/dashboard/courses'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/instructor/capstones'
    | '/_authenticated/instructor/courses'
    | '/_authenticated/instructor/students'
    | '/_authenticated/instructor/upload'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/instructor/'
    | '/_authenticated/dashboard/courses/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScholarshipRoute: typeof ScholarshipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scholarship': {
      id: '/scholarship'
      path: '/scholarship'
      fullPath: '/scholarship'
      preLoaderRoute: typeof ScholarshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/virtual-assistant-programme': {
      id: '/courses/virtual-assistant-programme'
      path: '/virtual-assistant-programme'
      fullPath: '/courses/virtual-assistant-programme'
      preLoaderRoute: typeof CoursesVirtualAssistantProgrammeRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/scrum-master': {
      id: '/courses/scrum-master'
      path: '/scrum-master'
      fullPath: '/courses/scrum-master'
      preLoaderRoute: typeof CoursesScrumMasterRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/project-management-business-analysis': {
      id: '/courses/project-management-business-analysis'
      path: '/project-management-business-analysis'
      fullPath: '/courses/project-management-business-analysis'
      preLoaderRoute: typeof CoursesProjectManagementBusinessAnalysisRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/product-management': {
      id: '/courses/product-management'
      path: '/product-management'
      fullPath: '/courses/product-management'
      preLoaderRoute: typeof CoursesProductManagementRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/digital-marketing': {
      id: '/courses/digital-marketing'
      path: '/digital-marketing'
      fullPath: '/courses/digital-marketing'
      preLoaderRoute: typeof CoursesDigitalMarketingRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/data-analysis': {
      id: '/courses/data-analysis'
      path: '/data-analysis'
      fullPath: '/courses/data-analysis'
      preLoaderRoute: typeof CoursesDataAnalysisRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/cybersecurity': {
      id: '/courses/cybersecurity'
      path: '/cybersecurity'
      fullPath: '/courses/cybersecurity'
      preLoaderRoute: typeof CoursesCybersecurityRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/ai-for-professionals': {
      id: '/courses/ai-for-professionals'
      path: '/ai-for-professionals'
      fullPath: '/courses/ai-for-professionals'
      preLoaderRoute: typeof CoursesAiForProfessionalsRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instructor/': {
      id: '/_authenticated/instructor/'
      path: '/instructor'
      fullPath: '/instructor/'
      preLoaderRoute: typeof AuthenticatedInstructorIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instructor/upload': {
      id: '/_authenticated/instructor/upload'
      path: '/instructor/upload'
      fullPath: '/instructor/upload'
      preLoaderRoute: typeof AuthenticatedInstructorUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instructor/students': {
      id: '/_authenticated/instructor/students'
      path: '/instructor/students'
      fullPath: '/instructor/students'
      preLoaderRoute: typeof AuthenticatedInstructorStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instructor/courses': {
      id: '/_authenticated/instructor/courses'
      path: '/instructor/courses'
      fullPath: '/instructor/courses'
      preLoaderRoute: typeof AuthenticatedInstructorCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instructor/capstones': {
      id: '/_authenticated/instructor/capstones'
      path: '/instructor/capstones'
      fullPath: '/instructor/capstones'
      preLoaderRoute: typeof AuthenticatedInstructorCapstonesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/courses': {
      id: '/_authenticated/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof AuthenticatedDashboardCoursesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/certificates': {
      id: '/_authenticated/dashboard/certificates'
      path: '/certificates'
      fullPath: '/dashboard/certificates'
      preLoaderRoute: typeof AuthenticatedDashboardCertificatesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/lessons': {
      id: '/_authenticated/admin/lessons'
      path: '/admin/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AuthenticatedAdminLessonsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/inquiries': {
      id: '/_authenticated/admin/inquiries'
      path: '/admin/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AuthenticatedAdminInquiriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/enrollments': {
      id: '/_authenticated/admin/enrollments'
      path: '/admin/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AuthenticatedAdminEnrollmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/cohorts': {
      id: '/_authenticated/admin/cohorts'
      path: '/admin/cohorts'
      fullPath: '/admin/cohorts'
      preLoaderRoute: typeof AuthenticatedAdminCohortsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/certificates': {
      id: '/_authenticated/admin/certificates'
      path: '/admin/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AuthenticatedAdminCertificatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/capstones': {
      id: '/_authenticated/admin/capstones'
      path: '/admin/capstones'
      fullPath: '/admin/capstones'
      preLoaderRoute: typeof AuthenticatedAdminCapstonesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/courses/$slug': {
      id: '/_authenticated/dashboard/courses/$slug'
      path: '/$slug'
      fullPath: '/dashboard/courses/$slug'
      preLoaderRoute: typeof AuthenticatedDashboardCoursesSlugRouteImport
      parentRoute: typeof AuthenticatedDashboardCoursesRoute
    }
  }
}

interface AuthenticatedDashboardCoursesRouteChildren {
  AuthenticatedDashboardCoursesSlugRoute: typeof AuthenticatedDashboardCoursesSlugRoute
}

const AuthenticatedDashboardCoursesRouteChildren: AuthenticatedDashboardCoursesRouteChildren =
  {
    AuthenticatedDashboardCoursesSlugRoute:
      AuthenticatedDashboardCoursesSlugRoute,
  }

const AuthenticatedDashboardCoursesRouteWithChildren =
  AuthenticatedDashboardCoursesRoute._addFileChildren(
    AuthenticatedDashboardCoursesRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardCertificatesRoute: typeof AuthenticatedDashboardCertificatesRoute
  AuthenticatedDashboardCoursesRoute: typeof AuthenticatedDashboardCoursesRouteWithChildren
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardCertificatesRoute:
      AuthenticatedDashboardCertificatesRoute,
    AuthenticatedDashboardCoursesRoute:
      AuthenticatedDashboardCoursesRouteWithChildren,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminCapstonesRoute: typeof AuthenticatedAdminCapstonesRoute
  AuthenticatedAdminCertificatesRoute: typeof AuthenticatedAdminCertificatesRoute
  AuthenticatedAdminCohortsRoute: typeof AuthenticatedAdminCohortsRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminEnrollmentsRoute: typeof AuthenticatedAdminEnrollmentsRoute
  AuthenticatedAdminInquiriesRoute: typeof AuthenticatedAdminInquiriesRoute
  AuthenticatedAdminLessonsRoute: typeof AuthenticatedAdminLessonsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedInstructorCapstonesRoute: typeof AuthenticatedInstructorCapstonesRoute
  AuthenticatedInstructorCoursesRoute: typeof AuthenticatedInstructorCoursesRoute
  AuthenticatedInstructorStudentsRoute: typeof AuthenticatedInstructorStudentsRoute
  AuthenticatedInstructorUploadRoute: typeof AuthenticatedInstructorUploadRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedInstructorIndexRoute: typeof AuthenticatedInstructorIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminCapstonesRoute: AuthenticatedAdminCapstonesRoute,
  AuthenticatedAdminCertificatesRoute: AuthenticatedAdminCertificatesRoute,
  AuthenticatedAdminCohortsRoute: AuthenticatedAdminCohortsRoute,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
  AuthenticatedAdminEnrollmentsRoute: AuthenticatedAdminEnrollmentsRoute,
  AuthenticatedAdminInquiriesRoute: AuthenticatedAdminInquiriesRoute,
  AuthenticatedAdminLessonsRoute: AuthenticatedAdminLessonsRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedInstructorCapstonesRoute: AuthenticatedInstructorCapstonesRoute,
  AuthenticatedInstructorCoursesRoute: AuthenticatedInstructorCoursesRoute,
  AuthenticatedInstructorStudentsRoute: AuthenticatedInstructorStudentsRoute,
  AuthenticatedInstructorUploadRoute: AuthenticatedInstructorUploadRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedInstructorIndexRoute: AuthenticatedInstructorIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CoursesRouteChildren {
  CoursesAiForProfessionalsRoute: typeof CoursesAiForProfessionalsRoute
  CoursesCybersecurityRoute: typeof CoursesCybersecurityRoute
  CoursesDataAnalysisRoute: typeof CoursesDataAnalysisRoute
  CoursesDigitalMarketingRoute: typeof CoursesDigitalMarketingRoute
  CoursesProductManagementRoute: typeof CoursesProductManagementRoute
  CoursesProjectManagementBusinessAnalysisRoute: typeof CoursesProjectManagementBusinessAnalysisRoute
  CoursesScrumMasterRoute: typeof CoursesScrumMasterRoute
  CoursesVirtualAssistantProgrammeRoute: typeof CoursesVirtualAssistantProgrammeRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesAiForProfessionalsRoute: CoursesAiForProfessionalsRoute,
  CoursesCybersecurityRoute: CoursesCybersecurityRoute,
  CoursesDataAnalysisRoute: CoursesDataAnalysisRoute,
  CoursesDigitalMarketingRoute: CoursesDigitalMarketingRoute,
  CoursesProductManagementRoute: CoursesProductManagementRoute,
  CoursesProjectManagementBusinessAnalysisRoute:
    CoursesProjectManagementBusinessAnalysisRoute,
  CoursesScrumMasterRoute: CoursesScrumMasterRoute,
  CoursesVirtualAssistantProgrammeRoute: CoursesVirtualAssistantProgrammeRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScholarshipRoute: ScholarshipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
